### ISSUE TITLE
Uncaught ReferenceError: Peer is not defined

### ISSUE THREAD

**Issue by cr7rahul** [heyletscode/android-video-call-app#1]
Getting this error

Uncaught ReferenceError: Peer is not defined
at init (call.js:12)
    at <anonymous>:1:1

when i do init("1")

I used the same code as in your project, updated the ipaddress and the project location

**Comment by heyletscode** [comment]
Share your project file

**Comment by cr7rahul** [comment]
I found out the issue. In call.html  in put `<script src="./peerjs.js"></script>` it should have been ` <script src="./peer.js"></script>`

But now i'm facing another issue 

WebSocket connection to 'ws://192.168.xx.xx:9000/C:/USER/Projects/Android/VideoCalling/Server/peerjs?key=peerjs&id=1&token=sa0eg1ut4xs' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by heyletscode** [comment]
your peerjs file name is “peer.js” but in the html you’re referring it as
“peerjs.js” you can either change the file name to “peerjs.js” or change
the name in html to “peer.js”

**Comment by cr7rahul** [comment]
Yes i've update it but not getting another error.

WebSocket connection to 'ws://192.168.xx.xx:9000/C:/USER/Projects/Android/VideoCalling/Server/peerjs?key=peerjs&id=1&token=sa0eg1ut4xs' failed: Error during WebSocket handshake: Unexpected response code: 400
